import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import LatestProjects from "../components/latestProjects";
import IndexServices from "../components/indexServices";
import IndexAbout from "../components/indexAbout";
import Hero from "../components/hero";
import Footer from "../components/footer";
import { motion } from "framer-motion";
export default function Home() {
  const variants = {};
  return (
    <>
      <Head>
        <title>Will - Portfolio 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.main
        variants={variants}
        initial={"initial"}
        animate={"animate"}
        exit={"exit"}
        key={"main"}
      >
        <Hero />
        <LatestProjects />
        <IndexServices />
        <IndexAbout />
        <Footer />
      </motion.main>
    </>
  );
}
