import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import LatestProjects from "../components/latestProjects";
import IndexServices from "../components/indexServices";
export default function Home() {
  return (
    <>
      <Head>
        <title>Will - Portfolio 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.heroContianer}></section>
        <LatestProjects />
        <IndexServices />
      </main>
    </>
  );
}
